pipeline {
    agent {
        docker { image 'fugue/regula:v0.8.0' }
    }
    stages {
        stage('Test') {
            steps {
                sh 'mkdir reports'
                sh 'regula run -u  --include policy/s3_bucket_prefix.rego --format junit tf > reports/output.xml'
            }
        }
    }
    post {
        always {
            junit 'reports/*.xml'
        }
    }
}